In [2]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
df=pd.read_csv(r"C:\Users\esair\Downloads\retail_sales_dataset.csv")
df

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150


In [ ]:
x=df[['Age','Quantity','Total Amount','Price per Unit']]
y=df['Product Category']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train,x_valid,y_train,y_valid=train_test_split(x_train,y_train,test_size=0.25,random_state=42)
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_valid=scaler.transform(x_valid)
x_test=scaler.transform(x_test)
model=KNeighborsClassifier(n_neighbors=1)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.355
              precision    recall  f1-score   support

      Beauty       0.23      0.28      0.25        54
    Clothing       0.46      0.41      0.43        80
 Electronics       0.36      0.35      0.35        66

    accuracy                           0.35       200
   macro avg       0.35      0.35      0.35       200
weighted avg       0.37      0.35      0.36       200

[[15 16 23]
 [29 33 18]
 [20 23 23]]


In [10]:
grid=GridSearchCV(
    estimator=KNeighborsClassifier(),
    param_grid={
        "n_neighbors":list(range(1,31))
    },
    cv=10,
    scoring='accuracy'
)
grid.fit(x_train, y_train)
print(grid.best_params_)
print(grid.best_score_)
print(grid.best_estimator_)
print(grid.cv_results_['mean_test_score'])

{'n_neighbors': 1}
0.3633333333333333
KNeighborsClassifier(n_neighbors=1)
[0.36333333 0.36166667 0.335      0.35       0.34833333 0.345
 0.32166667 0.31333333 0.34666667 0.33166667 0.34       0.33833333
 0.34166667 0.33       0.34666667 0.34833333 0.335      0.33166667
 0.33166667 0.32666667 0.335      0.33833333 0.345      0.35166667
 0.345      0.34666667 0.34166667 0.34166667 0.32666667 0.32666667]
